version: "3.8"

services:
  build:
    container_name: build
    build:
      context: .
      dockerfile: Dockerfile
      args:
          USER_ID: "${USER_ID}"
          GROUP_ID: "${GROUP_ID}"
          USERNAME: "${USERNAME}"
    user: "${USER_ID}:${GROUP_ID}"
    volumes:
      - ./artifacts:/opt/artifacts